[project]
name = "onboarding"
version = "0.1.0"
description = "Journeys and scripts for Platform Onboarding"
authors = [{ name = "Gerrit Vermeulen", email = "gerrit@reachdigitalhealth.org" }]
requires-python = "~=3.11.0"
readme = "README.md"
license = "MIT"
dependencies = [
    "black>=24.4.2,<25",
    "ruff>=0.5.4,<0.6",
    "pytest>=8.3.2,<9",
    "pyyaml>=6.0.1,<7",
    "yamllint>=1.35.1,<2",
    "flow-wrangler",
]

[tool.uv.sources]
flow-wrangler = { git = "ssh://git@github.com/praekeltfoundation/flow-wrangler.git" }
