---
# base_url: "https://whatsapp-praekelt-cloud.turn.io/"
base_url: "https://whatsapp-praekelt-cloud.turn.io/"
workspace_uuid: "db6aae74-7510-4987-8510-149f38a6cbee"
qa_url: https://content-repo-api-qa.prk-k8s.prd-p6t.org
prod_url: https://platform-mnch-contentrepo.prk-k8s.prd-p6t.org
stack_uuids:
  - name: "intro-and-welcome" # "Onboarding: Intro & Welcome"
    prod_uuid: REMOVETHIS-47111691-cb8d-4cf0-8ecc-ed6792108157
    qa_uuid: e2203073-f8b3-45f4-b19d-4079d5af368a
  - name: "intro-and-welcome-reminders" # "Onboarding: Intro & Welcome Reminders"
    prod_uuid: REMOVETHIS-d28a1658-18af-4552-a985-905cf040d50e
    qa_uuid: 8407c748-140f-43fa-b5f4-b5652e07f484
  - name: "profile-classifier" # "Onboarding: Profile Classifier"
    prod_uuid: REMOVETHIS-e1f6a4d6-f245-4203-aed5-6577bbd4d96a
    qa_uuid: c77efa62-1c9d-4ace-ae7a-4585e4e929d1
  - name: "exploring-tour" # "Onboarding: Exploring Tour"
    prod_uuid: REMOVETHIS-160ac3f4-ab18-4610-bbab-c003f79e1197
    qa_uuid: 359b3ff4-796d-4b80-91a6-15532c7bdb90
  - name: "exploring-tour-reminders" # "Onboarding: Exploring Tour Reminders"
    prod_uuid: REMOVETHIS-c68d4257-74e1-45da-8d49-951b012ec65e
    qa_uuid: 9a69c7bf-607a-4d9a-930b-0079a55e536c
  - name: "profile-pregnancy-health" # "Onboarding: Profile Pregnancy Health"
    prod_uuid: REMOVETHIS-2063ff09-4405-4cf2-9a57-12ffa00c99da
    qa_uuid: f582feb5-8605-4509-8279-ec17202b42a6
  - name: "profile-generic" # "Onboarding: Profile Generic"
    prod_uuid: REMOVETHIS-a7eae888-77a0-4e68-ac47-ceb03676bef1
    qa_uuid: 718e6b27-d818-40cf-8a7b-50c17bd236ba
  - name: "profile-hcw" # "Onboarding: Profile HCW"
    prod_uuid: REMOVETHIS-c4c8d015-2255-4aeb-94be-eb0b7a2174e0
    qa_uuid: 9aa596d3-40f0-4349-8322-e44d1fd1d127
  - name: "profile-hcw-nudge" # "Onboarding: HCW Reminder"
    prod_uuid: REMOVETHIS-97e8ba1c-5638-4515-bd5d-ca6aca01e7f8
    qa_uuid: 03656be1-d528-453b-b7f7-efd3cbbf1123
  - name: "profile-pregnant-nurse" # "Onboarding: Profile Pregnant Nurse"
    prod_uuid: REMOVETHIS-8e71f3ab-9d34-491e-930a-2b1435a9afed
    qa_uuid: 1ed10e1b-f812-4730-8ec5-3f46088c41c7
  - name: "profile-pregnant-nurse-reminder" # "Onboarding: Profile Pregnant Nurse Reminder"
    prod_uuid: REMOVETHIS-d7cc2c04-5931-4910-9f1e-0cebbb80d1f8
    qa_uuid: 107bebf6-eb76-4886-a0ee-1a11067fe089
  - name: "opt-in-reminder" # "Onboarding: Opt In Reminder"
    prod_uuid: REMOVETHIS-3ef42a80-1039-4193-9ad3-4ff56b80de2e
    qa_uuid: f36d4d47-9cc7-4202-a73f-db6f03e478cd
  - name: "re-engagement" # "Onboarding: Re Engagement"
    prod_uuid: REMOVETHIS-78cca41f-d27d-4669-ae16-a785744047a1
    qa_uuid: 689e019d-beb5-4ba2-8c04-f4663a67ab81
  - name: "edd-reminders" # "Onboarding: EDD Reminders"
    prod_uuid: REMOVETHIS-5b67121a-b097-4eec-9493-e948f71d3c6f
    qa_uuid: 99754af5-1696-48c8-8562-4b52c13db61d
  - name: "menu-personalised" # "Onboarding: Personalised Menu"
    prod_uuid: REMOVETHIS-31bfb947-74a5-4b3b-8dec-def4b7732fd5
    qa_uuid: bd10611d-73b6-4c56-a4ca-41d4136d0d6a
  - name: "menu-non-personalised" # "Onboarding: Non Personalised Menu"
    prod_uuid: REMOVETHIS-d02746ff-a3e2-4153-99ff-cd01a941a00d
    qa_uuid: 141a7271-30ec-4b31-83a5-11e4fa655df7
  - name: "profile" # "Onboarding: Your Profile"
    prod_uuid: REMOVETHIS-f085a8b1-5e73-408d-bcc2-9487d0512085
    qa_uuid: 90d3135d-6c0c-43c2-b2a8-a099d63639bf
  - name: "basic-questions" # "Onboarding: Basic Profile Questions"
    prod_uuid: REMOVETHIS-fe7139a4-60c5-4ced-ad82-daa43f483c37
    qa_uuid: 74bd3d95-2aec-4174-ad32-926952c795ca
  - name: "personal-profile-questions" # "Onboarding: Personal Profile Questions"
    prod_uuid: REMOVETHIS-67e29cda-52a9-4eb4-9fc0-224c44585c8c
    qa_uuid: e1e033d4-897a-4c9b-9eea-2411458c3c4c
  - name: "menu-redirect" # "Onboarding: Menu Redirect"
    prod_uuid: REMOVETHIS-75eada25-7a3e-4df8-a19c-39ace798427d
    qa_uuid: fb98bb9d-60a6-47a1-a474-bb0f45b80030
  - name: "dma-form" # DMA Form
    prod_uuid: REMOVETHIS-b283e7c1-0a79-45ab-976c-5566d9ba06cd
    qa_uuid: 9bd8c27a-d08e-4c9e-8623-b4007373437e
  - name: "quiz-breastfeeding" # Quiz: Breastfeeding
    prod_uuid: REMOVETHIS-todo
    qa_uuid: 6a002d8f-dd9d-4648-96d2-148e9deeed5e