name: Continuous integration
on:
  push:
    branches: ["*"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  flow-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - elixir-version: "1.17"
            otp-version: "27"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir-version }}
          otp-version: ${{ matrix.otp-version }}

      - name: Fetch flow tester
        uses: actions/checkout@v4
        with:
          repository: praekeltfoundation/flow_tester
          ref: v0.3.0
          path: flow_tester
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test flows
        run: |
          ./flow_tester/run_flow_tests.exs HelpCentre/QA/tests/ Onboarding/QA/tests/ 
          
